{{cookiecutter.project_slug}}/docker-compose.yaml
{{cookiecutter.project_slug}}/nginx/Dockerfile
{{cookiecutter.project_slug}}/nginx/default.conf
{{cookiecutter.project_slug}}/nginx/paths.conf

- Updated nginx external port on `docker-compose.yaml` from `80/443` to `8080/8443` to avoid local processes conflict on same port.
- Remove unnecessary volume mounts for nginx image (nginx not reload itself if mounted config file changes).
- Added `paths.conf` to avoid duplicated code for HTTP and HTTPS protocol (we don't wanna force redirect from HTTP to HTTPS for development env).
- Added configuration for `/sockjs-node` path (nginx) to fix ReactJS hot-reload.

Upgrade nginx configuration

---

hooks/pre_gen_project.py
tests/test_generator.py
{{cookiecutter.project_slug}}/scripts/add_cluster.sh
{{cookiecutter.project_slug}}/scripts/python/add_cluster.py
{{cookiecutter.project_slug}}/scripts/python/gitlab_sync.py

Some bug about gitlab and kubernetes link fixed
Coverage badge page url changed

Changing gitlab stuff configurations

---

{{cookiecutter.project_slug}}/Makefile

hotfix for Makefile

---

{{cookiecutter.project_slug}}/README.md
{{cookiecutter.project_slug}}/SETUP.md

* Update SETUP.md
* Fix README typos
Co-authored-by: Raffaele Colace <raffaele@20tab.com>
Co-authored-by: Paolo Melchiorre <paolo@melchiorre.org>

Fix README.md typos and rephrase lines in SETUP.md

---

{{cookiecutter.project_slug}}/SETUP.md
{{cookiecutter.project_slug}}/scripts/k8s_setup.sh
{{cookiecutter.project_slug}}/scripts/python/k8s_setup.py

I added a draft script for the k8s setup

Fix #64 Add k8s setup script

---

{{cookiecutter.project_slug}}/k8s/2_secrets.yaml_template

Fix #99 Imrpove S3 overwrite variable

---

{{cookiecutter.project_slug}}/SETUP.md
{{cookiecutter.project_slug}}/k8s/cluster/fluentd/1_fluentd-secrets.yaml_template
{{cookiecutter.project_slug}}/k8s/cluster/fluentd/2_fluentd-configmap.yaml
{{cookiecutter.project_slug}}/k8s/cluster/fluentd/3_fluentd-daemonset-forward.yaml

* K8s fluentd daemonset yaml
* Cluster level logging
* Update docker image
* Update SETUP.md
Co-authored-by: Carmelo Catalfamo <carmelo@20tab.com>
Co-authored-by: Paolo Melchiorre <paolo@20tab.com>

K8s fluentd daemonset yaml (#85)

---

{{cookiecutter.project_slug}}/k8s/2_secrets.yaml_template

Fix #106 - Typo in secrets yaml template

Fix #106 - Typo in secrets yaml template

---

{{cookiecutter.project_slug}}/.env_template
{{cookiecutter.project_slug}}/docker-compose.yaml

Add uWSGI auto reload to dev env

---

{{cookiecutter.project_slug}}/.gitignore

Gitignore devcontainer file and folder

---

{{cookiecutter.project_slug}}/.env_template

Fix UWSGI_PY_AUTO_RELOAD template var placement

---

{{cookiecutter.project_slug}}/nginx/paths.conf

As agreed, the forwarded ssl proxy headers have been fixed.

Fix local nginx proxy ssl header

---

hooks/pre_gen_project.py
{{cookiecutter.project_slug}}/scripts/python/gitlab_sync.py

Fix https://github.com/20tab/20tab-standard-project/issues/138

Fix issue #138

---

.github/workflows/publish-docker-image.yml
.github/workflows/test.yml

Add Github action for Test and Docker Image

---

{{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/database-dump-cronjob/main.tf

Set successful_jobs_history_limit to 31

Improve postgresql dump cron

---

{{cookiecutter.project_dirname}}/.env_template

TG-446 Use iPython's core debugger

---

{{cookiecutter.project_dirname}}/scripts/deploy/vault.sh

Fix the Vault TFC backend path.

Fix Vault TFC backend path

---

terraform/vault-admin/main.tf
terraform/vault-admin/variables.tf
{{cookiecutter.project_dirname}}/terraform/environment/digitalocean-k8s/main.tf
{{cookiecutter.project_dirname}}/terraform/environment/digitalocean-k8s/variables.tf
{{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/database-dump-cronjob/main.tf
{{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/database-dump-cronjob/variables.tf
{{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/postgres/main.tf
{{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/postgres/outputs.tf
{{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/redis/main.tf
{{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/redis/outputs.tf
{{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/redis/variables.tf
{{cookiecutter.project_dirname}}/terraform/environment/other-k8s/main.tf
{{cookiecutter.project_dirname}}/terraform/environment/vars/.tfvars

Add postgis support
And fix minors on pg_dump cronjob

TG-665 Add postgis support

---

{{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/monitoring/main.tf

Make it compatible with k8s 1.25

Upgrade loki version

---

{{cookiecutter.project_dirname}}/terraform/base/digitalocean-k8s/variables.tf
{{cookiecutter.project_dirname}}/terraform/environment/digitalocean-k8s/main.tf
{{cookiecutter.project_dirname}}/terraform/environment/digitalocean-k8s/variables.tf
{{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/monitoring/main.tf
{{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/routing/main.tf
{{cookiecutter.project_dirname}}/terraform/environment/modules/kubernetes/routing/variables.tf
{{cookiecutter.project_dirname}}/terraform/environment/other-k8s/main.tf
{{cookiecutter.project_dirname}}/terraform/environment/other-k8s/variables.tf

Tested on knowledge-share project

Fix non-www redirect support
